#!/usr/bin/env python3
"""Minimal PE32 export-table parser.

Used to generate .def files for the Windows Mobile / WinCE port from the
stock HTC HD2 (Adreno 200) driver DLLs.  Emits "name @ordinal" pairs so
arm-mingw32ce-dlltool can build link-by-name import libraries.

Usage:
    pe_exports.py <file.dll> [--def <LIBNAME>] [--names-only]
"""

import struct
import sys


def u16(b, o):
    return struct.unpack_from('<H', b, o)[0]


def u32(b, o):
    return struct.unpack_from('<I', b, o)[0]


class PE(object):
    def __init__(self, data):
        self.data = data
        if data[:2] != b'MZ':
            raise ValueError('not an MZ image')
        pe = u32(data, 0x3C)
        if data[pe:pe + 4] != b'PE\0\0':
            raise ValueError('bad PE signature')
        self.machine = u16(data, pe + 4)
        nsec = u16(data, pe + 6)
        opt_size = u16(data, pe + 20)
        opt = pe + 24
        magic = u16(data, opt)
        if magic != 0x10B:
            raise ValueError('only PE32 supported (magic 0x%X)' % magic)
        # PE32 optional header: data directories start at offset 96
        self.dd = opt + 96
        # Section table follows the optional header
        self.sections = []
        sec = opt + opt_size
        for i in range(nsec):
            o = sec + i * 40
            name = data[o:o + 8].rstrip(b'\0').decode('latin-1')
            vsize, vaddr, rsize, raddr = struct.unpack_from('<IIII', data, o + 8)
            self.sections.append((name, vaddr, vsize, raddr, rsize))

    def rva2off(self, rva):
        for name, vaddr, vsize, raddr, rsize in self.sections:
            # Use the raw size as the bound: virtual size may be padded and
            # rounded up past what actually exists in the file.
            if vaddr <= rva < vaddr + max(vsize, rsize):
                off = rva - vaddr + raddr
                if off < len(self.data):
                    return off
        return None

    def cstr(self, rva):
        o = self.rva2off(rva)
        if o is None:
            return None
        e = self.data.index(b'\0', o)
        return self.data[o:e].decode('latin-1')

    def exports(self):
        """Return (dll_name, [(name_or_None, ordinal, forward_or_None)])."""
        edir_rva = u32(self.data, self.dd + 0)
        edir_size = u32(self.data, self.dd + 4)
        if not edir_rva or not edir_size:
            return (None, [])
        e = self.rva2off(edir_rva)
        if e is None:
            raise ValueError('export directory RVA 0x%X unmapped' % edir_rva)

        name_rva = u32(self.data, e + 12)
        base = u32(self.data, e + 16)
        nfuncs = u32(self.data, e + 20)
        nnames = u32(self.data, e + 24)
        afuncs = u32(self.data, e + 28)
        anames = u32(self.data, e + 32)
        aords = u32(self.data, e + 36)

        dll = self.cstr(name_rva) if name_rva else None

        # ordinal (biased) -> exported name
        ord2name = {}
        if nnames and anames and aords:
            no = self.rva2off(anames)
            oo = self.rva2off(aords)
            for i in range(nnames):
                nm = self.cstr(u32(self.data, no + i * 4))
                ord2name[u16(self.data, oo + i * 2) + base] = nm

        out = []
        fo = self.rva2off(afuncs)
        for i in range(nfuncs):
            fn_rva = u32(self.data, fo + i * 4)
            if fn_rva == 0:
                continue  # hole in the address table
            ordinal = base + i
            fwd = None
            # A function RVA landing inside the export directory is a forwarder
            if edir_rva <= fn_rva < edir_rva + edir_size:
                fwd = self.cstr(fn_rva)
            out.append((ord2name.get(ordinal), ordinal, fwd))
        return (dll, out)


MACHINE = {0x1C0: 'ARM', 0x1C2: 'ARM/Thumb', 0x1C4: 'ARMv7', 0x14C: 'i386'}


def main():
    argv = sys.argv[1:]
    if not argv:
        sys.stderr.write(__doc__)
        return 2
    path = argv[0]
    as_def = '--def' in argv
    names_only = '--names-only' in argv
    libname = None
    if as_def:
        i = argv.index('--def')
        if i + 1 < len(argv):
            libname = argv[i + 1]

    with open(path, 'rb') as f:
        pe = PE(f.read())
    dll, exps = pe.exports()

    named = [(n, o, f) for (n, o, f) in exps if n]
    noname = [(n, o, f) for (n, o, f) in exps if not n]

    if names_only:
        for n, o, f in sorted(named):
            print(n)
        return 0

    if as_def:
        print('; Auto-generated by pe_exports.py from %s' % path.split('/')[-1])
        print('; %d named exports, %d by-ordinal-only' % (len(named), len(noname)))
        print('LIBRARY %s' % (libname or dll or path.split('/')[-1]))
        print('EXPORTS')
        for n, o, f in sorted(named):
            print('    %-34s @%d' % (n, o))
        return 0

    print('file      : %s' % path)
    print('machine   : 0x%X (%s)' % (pe.machine, MACHINE.get(pe.machine, '?')))
    print('dll name  : %s' % dll)
    print('exports   : %d named, %d ordinal-only' % (len(named), len(noname)))
    fwds = [(n, o, f) for (n, o, f) in exps if f]
    if fwds:
        print('forwarders: %d' % len(fwds))
        for n, o, f in fwds[:20]:
            print('    %s @%d -> %s' % (n, o, f))
    for n, o, f in sorted(named):
        print('  @%-5d %s' % (o, n))
    return 0


if __name__ == '__main__':
    sys.exit(main())
